### PR TITLE
Solve error memory and curl.

### PR DESCRIPTION
**Pull request by paulorwd**
Just was changed the way to save the file, both are pretty much the same function, only to remove the curl error with the memory.

### CODE REVIEW

**Comment by krizalys** [comment]
Hi @paulorwd, thanks for your pull request.

Note that trading `php://memory` for `php://temp` also has performance implications, since the latter may create a file (slow operation). More info here: http://php.net/manual/en/wrappers.php.php

Could you please tell me more about the error you are getting with `php://memory`? There may be another solution to fix it.

In any case, if you still like the idea of relying on temporary files rather than memory, I propose that you adjust your pull request to let the user choose their stream policy.

**Comment by DavidAnderson684** [comment]
I think it's likely that a true solution to @paulorwd's problem would be to implement chunked uploading. If a file is too big for memory, then it probably also ought to be being sent in chunks instead of all-in-one.

**Comment by paulorwd** [comment]
That was the problem and the solution that solved the problem for me. In
fact the problem is not connected with the file size in my case I use for
small files, the problem was connected with the curl and memory.

http://stackoverflow.com/questions/6841854/how-to-do-curl-put-requests-with-a-php-memory-file-handle

Em qui, 26 de mai de 2016 às 13:53, David Anderson <notifications@github.com>
escreveu:

**Comment by krizalys** [comment]
@paulorwd Did you also try adding the `r` flag as the accepted answer of this SO question? I'd rather prefer this alternative if it works. Still, I'll be happy to merge this PR if you introduce a flag that lets users choose their strategy when it comes to uploading big files with low memory.

Also, as I'm not getting errors related to memory streams & cURL, can you give me more details about your configuration please?

@DavidAnderson684 Even if that does not seem to be the problem here, chunked uploads would definitely be a nice to have ;)

**Comment by paulorwd** [comment]
I had tried the first alternative, had no effect, but it would be interesting yes, put the play option and a parameter to the user to choose which one to use. As for the error, I can not tell you much about it because I was not looking much, not to waste time just made the change, I know only that it is error in php.

**Pull request merged**
