### PR TITLE
fetchDescendantObjects bugfix

### PR DESCRIPTION
**Pull request by uuf6429**
Minor fix to CURL/post requests and bugfix for `fetchDescendantObjects` recursive functionality.

### CODE REVIEW

**Comment by krizalys** [comment]
Thanks for the PR.

Could you please make it work on PHP 5.3 too? It should be as simple as replacing the `[]` by an old-school `array()`.

Nice catch for the `fetchDescendantObjects()` bug. Please could you also add a unit test to demonstrate the issue and how your change fixes it?

You may split the 2 tasks into 2 PRs if you wish. Thanks for your help.

**Comment by uuf6429** [comment]
Will do both in one, no problem.

**Comment by uuf6429** [comment]
@krizalys on a side note; protected property names do not conform with PSR-1..

**Comment by krizalys** [comment]
Merged, thanks for your work!
Will probably adjust a bit the coding style though :)

Also agree with making property names more PSR-friendly, although that's near the bottom of my priority list, hehehe.

**Comment by uuf6429** [comment]
@krizalys regarding code style, I suggest using something like [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) (maybe with a git pre-commit hook installed). Once you define your prefered style (in a .php_cs file), you can enforce it on collaborating devs.

**Pull request merged**
