### PR TITLE
Large file upload tests

### PR DESCRIPTION
**Pull request by Gotham25**
Added additional tests for UploadSessionProxy

### CODE REVIEW

**Comment by Gotham25** [comment]
Hi @krizalys. I have added some tests. Upon testing the uncovered cases, I found an issue with this line [here](https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Proxy/UploadSessionProxy.php#L117). I have fixed that now.

And I have added a static method inside the test class as a utility to provide sample file contents across added additional tests. Can you have a check and let me know if that's the right way to do it ?.

Meanwhile I'll have the style issue fixed.

**Comment by krizalys** [comment]
Thanks for the PR @Gotham25. I'll look into it shortly and let you know.

**Comment by Gotham25** [comment]
Styles are fixed now :)

**Comment by Gotham25** [comment]
Hey @krizalys , Any update on this ?

**Comment by krizalys** [comment]
Hi @Gotham25, thanks for the changes, I have been looking into it - should finish this week end.

**Pull request merged**
