### PR TITLE
Bump php version

### PR DESCRIPTION
**Pull request by aarreedd**
Thanks for your pull request!

Before we consider merging it, please take the time to ensure you are complying
with these guidelines:

* [ ] I have described my changes in the
  [CHANGELOG](https://github.com/krizalys/onedrive-php-sdk/blob/master/CHANGELOG.md)
* [ ] I have adopted the
  [coding style](https://github.com/krizalys/onedrive-php-sdk/tree/master/doc/CodingStyle.md)
* [ ] I have followed the [contributor
  rules](https://github.com/krizalys/onedrive-php-sdk/tree/master/doc/ContributorRules.md)
* [ ] I have added consistent [PHPDoc](https://www.phpdoc.org/) documentation to
  symbols I added
* [ ] I have fixed an issue and I added [unit test
  case(s)](https://github.com/krizalys/onedrive-php-sdk/tree/master/test/unit)
* [ ] I have added a feature and I added [functional test
  case(s)](https://github.com/krizalys/onedrive-php-sdk/tree/master/test/functional)
* [ ] I have passed all continuous integration checks or discussed with project
  maintainers of special treatments for exceptional cases
* [ ] I accept my contribution to be code-reviewed by project maintainers and
  will refine it as requested
* [ ] I accept my pull request to be rejected at the project maintainers'
  discretion, **even if it complies with all the above guidelines**

**Failure to comply with the above guidelines will lead to your pull request
being either modified for compliance, ignored until modified for compliance,
and/or rejected altogether.**

### CODE REVIEW

**Comment by krizalys** [comment]
@aarreedd: PHP 8 is already supported since version 3, why do you think we need this change?

**Comment by aarreedd** [comment]
Composer is complaining that this package does not support php 8. This change fixes that.

**Comment by krizalys** [comment]
@aarreedd I tried to require this package from PHP 8 container and was unable to reproduce such an issue:

```
$ php --version
PHP 8.0.3 (cli) (built: Apr 15 2021 00:06:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies

$ ./composer.phar --version
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Composer version 2.0.8 2020-12-03 17:20:38

$ ./composer.phar create-project
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files

$ ./composer.phar require krizalys/onedrive-php-sdk
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Using version ^3.1 for krizalys/onedrive-php-sdk
./composer.json has been updated
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Running composer update krizalys/onedrive-php-sdk
Loading composer repositories with package information
Updating dependencies
Lock file operations: 8 installs, 0 updates, 0 removals
  - Locking guzzlehttp/guzzle (7.3.0)
  - Locking guzzlehttp/promises (1.4.1)
  - Locking guzzlehttp/psr7 (1.8.2)
  - Locking krizalys/onedrive-php-sdk (3.1.0)
  - Locking microsoft/microsoft-graph (1.33.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking ralouphie/getallheaders (3.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 8 installs, 0 updates, 0 removals
  - Downloading guzzlehttp/promises (1.4.1)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading psr/http-message (1.0.1)
  - Downloading guzzlehttp/psr7 (1.8.2)
  - Downloading psr/http-client (1.0.1)
  - Downloading guzzlehttp/guzzle (7.3.0)
  - Downloading microsoft/microsoft-graph (1.33.0)
  - Downloading krizalys/onedrive-php-sdk (3.1.0)
  - Installing guzzlehttp/promises (1.4.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (1.8.2): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.3.0): Extracting archive
  - Installing microsoft/microsoft-graph (1.33.0): Extracting archive
  - Installing krizalys/onedrive-php-sdk (3.1.0): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
```

What version of Composer are you using? Please can you share your `composer.json` file and the errors produced by Composer?

**Comment by aarreedd** [comment]
You are correct. I thought I upgraded to the latest version of this package but I was still using version 2. Thank you!

**Pull request closed without merging**
