### PR TITLE
add 200 to allowed status codes

### PR DESCRIPTION
**Pull request by ardabeyazoglu**

### CODE REVIEW

**Comment by ardabeyazoglu** [comment]
Hi again, 
Are you going to merge this ? or is there anything you expect me to do ?

**Comment by krizalys** [comment]
Do you know how I can trigger an HTTP 200 from the API so I can try your change?

**Comment by ardabeyazoglu** [comment]
You can test for example `createFolder` with `"@microsoft.graph.conflictBehavior" => "replace"`, which is what i also do.

**Comment by krizalys** [comment]
Thanks for the PR & details @ardabeyazoglu, I finally merged after I have had a chance to cover these scenarios in functional test cases (see https://github.com/krizalys/onedrive-php-sdk/commit/c584ec8ed98d3d86f2e94f8605b3a3ce9001f5bc).

**Comment by ardabeyazoglu** [comment]
No problem. I may soon add some more useful stuff like uploading large files. I am already using in production, i just need to shape it a little bit.

**Comment by krizalys** [comment]
Thanks for the initiative, you may be interested by this PR: https://github.com/krizalys/onedrive-php-sdk/pull/52

**Pull request merged**
